name: Build

on:
  push:
    branches:
      - develop
    tags:
      - "*"

env:
  TARGET: default
  REGISTRY: ghcr.io
  REGISTRY_NAMESPACE: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      targets: ${{ steps.targets.outputs.matrix }}
      platforms: ${{ steps.platforms.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - id: targets
        name: Generate targets
        uses: docker/bake-action/subaction/matrix@v6
        with:
          target: ${{ env.TARGET }}

      - id: platforms
        name: Generate platforms
        uses: docker/bake-action/subaction/matrix@v6
        with:
          target: ${{ env.TARGET }}
          fields: platforms

  build:
    runs-on: ${{ startsWith(matrix.platforms, 'linux/arm') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}

    needs:
      - prepare

    strategy:
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.platforms) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Prepare
        run: |
          platform=${{ matrix.platforms }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - id: meta
        name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_NAMESPACE }}/${{ matrix.target }}

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: build
        name: Build Docker image
        uses: docker/bake-action@v6
        with:
          push: true
          source: .
          targets: ${{ matrix.target }}
          set: |
            *.platform=${{ matrix.platforms }}
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ fromJSON(steps.build.outputs.metadata)[matrix.target]['containerimage.digest'] }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.target }}-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest

    needs:
      - build
      - prepare

    strategy:
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.targets) }}

    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-${{ matrix.target }}-*
          merge-multiple: true

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: meta
        name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_NAMESPACE }}/${{ matrix.target }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_NAMESPACE }}/${{ matrix.target }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_NAMESPACE }}/${{ matrix.target }}:${{ steps.meta.outputs.version }}
